language: node_js
node_js: 12
branches:
  only: 
    - master
    - develop
script:
- yarn install
- yarn unit-test
before_deploy:
- yarn build
deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: e4ARuo2TOdZNo4BiTBYDgjjLhTolAomnhrKtFkYl1PL6ImCdgBRU2WG9j0gy9395Loq+0PcLZ7KyS6mQy2Tt6sgkyowYd7o1o1vbD9eSTLpPRH9IPntzRJzgD2GL1pRjB3ijhN8y7URzJ7Zw/YSwUxVvuzWzLi6c6dX1rrlfuTmCOeAs5bKcLJ8rp3bZQzR2MiMbAqAiybNRp4O+w/Jl7wL7ZU8OoKfEitPYIJAkJEHwQbQs2J8sYKlbrSet96bUaa/pWu13bO5DlhUFATTETtrJWXdxVHnLaWZIkURk/bSBwdmUMvuL9dxZgITG3IJ8YqdkrDpa2InEn9+sWPEgswzcoVHtAheWz2lCe1VW6LGBuHOHroCIV0sGy+SF23xbN3tEDBIHl0299A7c/EHgCMsET8wmIX3RvUTuR2GRE8AgKkeyGGhqQyGq0WnjU/dA3WMdmc5y9pvDelpyasEe3uWktO786E78Wr6KcIPZhomXxoYe8FOv3FIzJhWKQH7YB3vzXrICuMsyGXEy3DzYSwvIPdLNP2E9RjMvH4HQ6WTjtf9lWgP/rSmGw7tj6UjCzr0NFvk3Eo6xa+fHevUOTdpOHjOQg4RPF3KR4/3aaBxuPF/2WERpXNZEOVaFzLwDFAaOfLfspJcWkRDz3zkOmys9ZTdaLduS/7G2gRLtRGk=
  project: "${PROJECT_ID}"
  on:
    branch: master