language: node_js # set language to node_js
node_js:
  12 # use node version 12 current LTS
script: # run after installed
  - yarn install # install node module
  - yarn unit-test
before_deploy:
  - yarn build # build project
deploy:
  provider: firebase
  token:
    secure: ${FIREBASE_TOKEN}
  project: ${PROJECT_ID}
  on:
    branch: master
  